services:
  db:
    container_name: evermeet_postgres
    image: postgres
    environment:
      POSTGRES_USER: kris
      POSTGRES_PASSWORD: sa
      PGDATA: /data/postgres
    volumes:
      - ./db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge