spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/evermeet
    username: postgres
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true

logging:
  level:
    org:
      springframework:
        web: debug
    com: debug