spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/evermeet
    username: postgres
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
  cloud:
    azure:
      storage:
        blob:
          container-name: images
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  level:
    org:
      springframework:
        web: debug
    com: debug

azure:
  blob-storage:
    connection-string: BlobEndpoint=https://evermeetimagestorage.blob.core.windows.net/;QueueEndpoint=https://evermeetimagestorage.queue.core.windows.net/;FileEndpoint=https://evermeetimagestorage.file.core.windows.net/;TableEndpoint=https://evermeetimagestorage.table.core.windows.net/;SharedAccessSignature=sv=2022-11-02&ss=bfqt&srt=o&sp=rwdlacupiytfx&se=2026-04-08T21:57:57Z&st=2024-04-08T13:57:57Z&spr=https&sig=2pl1anJgPHsBrGqiM05qRBhdq4zAa0mPoMQZT%2BA7VYw%3D
