server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/evermeet
    username: postgres
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
  cloud:
    azure:
      storage:
        blob:
          container-name: images
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  profiles:
    active: dev


logging:
  level:
    org:
      springframework:
        web: debug
    com: debug

azure:
  blob-storage:
    connection-string: <Azure connection string>

